apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-bandwidth-operator
  namespace: longhorn-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: longhorn-bandwidth-operator
  namespace: longhorn-system
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn-bandwidth-operator
  namespace: longhorn-system
subjects:
- kind: ServiceAccount
  name: longhorn-bandwidth-operator
  namespace: longhorn-system
roleRef:
  kind: Role
  name: longhorn-bandwidth-operator
  apiGroup: rbac.authorization.k8s.io
